services:
  postgres:
    container_name: pg-container
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres-ugc:/var/lib/postgresql/data
      - ./docker/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/postgres-entrypoint.sh

volumes:
  postgres-ugc: